/*
 * Generated by erpcgen 1.12.0 on Sat Jun 22 14:36:07 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_helloworld_client_h_)
#define _c_helloworld_client_h_

#include "helloworld_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief helloworld identifiers */
enum _helloworld_ids
{
    khelloworld_service_id = 1,
    khelloworld_hello_id = 1,
};

//! @name helloworld
//@{
binary_t * hello(const binary_t * txInput);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void inithelloworld_client(erpc_client_t client);

void deinithelloworld_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_helloworld_client_h_
