/*
 * Generated by erpcgen 1.12.0 on Sat Jun 22 14:36:07 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_helloworld_server_h_)
#define _c_helloworld_server_h_

#include "helloworld_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief helloworld identifiers */
enum _helloworld_ids
{
    khelloworld_service_id = 1,
    khelloworld_hello_id = 1,
};

//! @name helloworld
//@{
binary_t * hello(const binary_t * txInput);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return helloworld_service service object. */
erpc_service_t create_helloworld_service(void);

/*! @brief Destroy helloworld_service service object. */
void destroy_helloworld_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_helloworld_server_h_
