/*
 * Generated by erpcgen 1.12.0 on Sat Jun 22 14:36:07 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_helloworld_interface_hpp_)
#define _helloworld_interface_hpp_

#include "helloworld_common.hpp"

namespace erpcShim
{


// Abstract base class for helloworld
class helloworld_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_helloId = 1;

        virtual ~helloworld_interface(void);

        virtual binary_t * hello(const binary_t * txInput) = 0;
private:
};
} // erpcShim


#endif // _helloworld_interface_hpp_
