/*
 * Generated by erpcgen 1.12.0 on Sat Jun 22 14:36:07 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_helloworld_server_hpp_)
#define _helloworld_server_hpp_

#include "helloworld_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11200 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for helloworld.
 */
class helloworld_service : public erpc::Service
{
public:
    helloworld_service(helloworld_interface *_helloworld_interface);

    virtual ~helloworld_service();

    /*! @brief return service interface handler. */
    helloworld_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    helloworld_interface *m_handler;
    /*! @brief Server shim for hello of helloworld interface. */
    erpc_status_t hello_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _helloworld_server_hpp_
