/*
 * Generated by erpcgen 1.12.0 on Sat Jun 22 14:36:07 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_helloworld_common_hpp_)
#define _helloworld_common_hpp_


#include <cstdbool>
#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11200 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_HELLOWORLD)
#define ERPC_TYPE_DEFINITIONS_HELLOWORLD

// Aliases data types declarations
typedef struct binary_t binary_t;

// Structures/unions data types declarations
struct binary_t
{
    uint8_t * data;
    uint32_t dataLength;
};


#endif // ERPC_TYPE_DEFINITIONS_HELLOWORLD


#endif // _helloworld_common_hpp_
