/*
 * Generated by erpcgen 1.12.0 on Sat Jun 22 14:36:07 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_helloworld_client_hpp_)
#define _helloworld_client_hpp_

#include "helloworld_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class helloworld_client: public helloworld_interface
{
    public:
        helloworld_client(erpc::ClientManager *manager);

        virtual ~helloworld_client();

        virtual binary_t * hello(const binary_t * txInput);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _helloworld_client_hpp_
